# Generated by Django 3.0 on 2020-08-01 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0002_remove_classroom_is_full'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='student',
        ),
    ]
